version: '3.3'

volumes:
  static:
  media:
  foodgram_pg:

services:

  db:
    container_name: foodgram_db_container
    image: postgres:13.10
    env_file: .env
    volumes:
      - foodgram_pg:/var/lib/postgresql/data

  backend:
    container_name: foodgram_backend_container
    build: ./backend/foodgram/
    env_file: .env
    volumes:
      - static:/static/
      - media:/media/
    depends_on:
      - db

  frontend:
    container_name: foodgram-front
    build: ./frontend/
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
    depends_on:
      - backend

  nginx:
    container_name: foodgram-proxy
    build: ./infra/
    ports:
      - 8080:80
    volumes:
      - static:/staticfiles/
    depends_on:
      - frontend
