# Generated by Django 5.1.4 on 2025-01-06 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_recipeshortlink_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeshortlink',
            name='code',
            field=models.CharField(default='1ba27e', max_length=10, unique=True),
        ),
    ]
