# Generated by Django 5.1.4 on 2025-01-07 16:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_alter_recipeshortlink_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientsinrecipe',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.ingredient', validators=[django.core.validators.MinValueValidator(2)], verbose_name='Ингредиент'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(help_text='Минимум 2 ингредиента | ', related_name='recipes', through='recipes.IngredientsInRecipe', to='recipes.ingredient', verbose_name='Ингредиенты'),
        ),
        migrations.AlterField(
            model_name='recipeshortlink',
            name='code',
            field=models.CharField(default='ad8010', max_length=10, unique=True),
        ),
    ]
