# Generated by Django 5.1.4 on 2025-01-07 19:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_alter_ingredientsinrecipe_ingredient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(help_text='Минимум 2 ингредиента | ', related_name='recipes', through='recipes.IngredientsInRecipe', to='recipes.ingredient', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Ингредиенты'),
        ),
        migrations.AlterField(
            model_name='recipeshortlink',
            name='code',
            field=models.CharField(default='ca8974', max_length=10, unique=True),
        ),
    ]
