# Generated by Django 5.1.4 on 2025-01-07 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_alter_recipe_ingredients_alter_recipeshortlink_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeshortlink',
            name='code',
            field=models.CharField(default='8a8dbd', max_length=10, unique=True),
        ),
    ]
