# Generated by Django 5.1.4 on 2025-02-09 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_alter_recipeshortlink_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeshortlink',
            name='code',
            field=models.CharField(default='ea08d1', max_length=10, unique=True),
        ),
    ]
