# Generated by Django 5.1.4 on 2025-02-09 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_alter_recipeshortlink_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeshortlink',
            name='code',
            field=models.CharField(default='6183d9', max_length=10, unique=True),
        ),
    ]
