# Generated by Django 5.1.4 on 2025-02-22 12:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0014_alter_recipeshortlink_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredientsinrecipe",
            name="amount",
            field=models.PositiveSmallIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(30),
                ],
                verbose_name="Количество",
            ),
        ),
        migrations.AlterField(
            model_name="ingredientsinrecipe",
            name="ingredient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="recipes.ingredient",
                verbose_name="Ингредиент",
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="cooking_time",
            field=models.PositiveSmallIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(240),
                ],
                verbose_name="Время приготовления в минутах",
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="ingredients",
            field=models.ManyToManyField(
                help_text="Минимум 2 ингредиента | ",
                related_name="recipes",
                through="recipes.IngredientsInRecipe",
                to="recipes.ingredient",
                verbose_name="Ингредиенты",
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="tags",
            field=models.ManyToManyField(
                help_text="Выберите не менее одного тега | ",
                related_name="recipes",
                to="recipes.tag",
                verbose_name="Теги",
            ),
        ),
        migrations.AlterField(
            model_name="recipeshortlink",
            name="code",
            field=models.CharField(default="7e9e31", max_length=10, unique=True),
        ),
    ]
