# Generated by Django 5.1.4 on 2025-02-22 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0015_alter_ingredientsinrecipe_amount_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="shoppingcart",
            old_name="owner",
            new_name="user",
        ),
        migrations.AlterField(
            model_name="recipeshortlink",
            name="code",
            field=models.CharField(default="321e11", max_length=10, unique=True),
        ),
    ]
