# Generated by Django 5.1.4 on 2025-02-23 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0015_alter_ingredientsinrecipe_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="code",
            field=models.CharField(default="1406ad", max_length=10, unique=True),
        ),
        migrations.DeleteModel(
            name="RecipeShortLink",
        ),
    ]
