# Generated by Django 5.1.4 on 2025-02-23 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_alter_customuser_first_name_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Subscriptions",
            new_name="Subscription",
        ),
    ]
