# Приложение users
MAX_LENGHT_NAME = 150
MAX_LENGHT_EMAIL = 254

# Приложение api
PAGE_SIZE = 6

# Приложение recipes
MAX_LENGHT_TAG = 32
MAX_LENGHT_INGREDIENT = 50
MAX_LENGHT_RECIPE_NAME = 256
MAX_LENGHT_RECIPE_CODE = 10
