# Приложение users
MAX_LENGHT_NAME = 150
MAX_LENGHT_EMAIL = 254

# Приложение api
PAGE_SIZE = 6

# Приложение recipes
MAX_LENGHT_TAG = 32
MAX_LENGHT_INGREDIENT_NAME = 128
MAX_LENGHT_INGREDIENT_M_UNIT = 64
MAX_LENGHT_RECIPE_NAME = 256
MAX_LENGHT_RECIPE_CODE = 10
