# Generated by Django 5.1.4 on 2025-09-01 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authtoken', '0003_tokenproxy'),
        ('recipes', '0003_favoriterecipe_created_shoppingcart_created_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomUser',
            new_name='User',
        ),
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together={('subscriber', 'author')},
        ),
    ]
